import type { NextPage } from "next";
import Head from "next/head";
import { Board } from "../src/components/Board";
import { Header } from "../src/components/Header";

const Home: NextPage = () => {
    return (
        <div className="flex flex-col h-screen">
            <Head>
                <title>App consultas</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className="flex-1 flex items-center justify-center">
                <Board />
            </main>
        </div>
    );
};

export default Home;
